### ISSUE TITLE
SetupJavaCaching breaks yaml workflow

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite-github-actions#3]
Found while testing recipe on https://github.com/murdos/easy-random-protobuf
![image](https://user-images.githubusercontent.com/155828/135687341-c66f8795-7ec9-4093-9a00-d24ab035c802.png)

**Comment by jkschneider** [comment]
This was supposed to be fixed by https://github.com/openrewrite/rewrite/commit/cda440d4aab0913b478556301cebae4946297fbc.

**Comment by jkschneider** [comment]
Looking good after the project was reingested

![image](https://user-images.githubusercontent.com/1697736/135691887-5107e6f9-5755-49ac-b73d-76dd6110ade7.png)
