### ISSUE TITLE
Add dependabot configuration

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#55]
This recipe should: 

1. Detect the build tools used (maven,gradle, npm, etc)
2. Create a default dependabot configuration for each one

I am not sure how to do this at this point, but I imagine that this could be archiable for projects using Github Actions

Projects that use Jenkins or others be harder

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#supported-repositories-and-ecosystems

**Comment by timtebeek** [comment]
Not sure I'd prioritize this one; I might just know a tool that handles both version numbers & the required code changes that I'd rather roll out. ;)

**Comment by sambsnyd** [comment]
As Tim says, I'd rather we replace dependabot than spread it.
I don't think we will implement this.

**Comment by yeikel** [comment]
I think that we can work together with dependabot. 

I do not think that dependabot competes with you given that not all upgrades will need code changes (ie bug fixes)
