### ISSUE TITLE
`PreferTemurinDistributions` should not be applied if Java 15 is used

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#68]
Temurin is not distributing Java 15. I ignore why that's the case but to avoid doing harm, this recipe should not be applied for that version

See https://adoptium.net/temurin/releases/ and https://github.com/Netflix/servo/pull/476

**Comment by yeikel** [comment]
This might be hard to implement when version matrix are used. In general, most projects should be moving away from Java 15

**Comment by timtebeek** [comment]
Seeing how I don't suppose anyone is using Java 15 very much these days I'm going to close this issue. Thanks for the suggestion!
