### ISSUE TITLE
AddCronTrigger - Add file matcher

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-github-actions#69]
Given a repo with multiple workflows, the goal is to add a cron trigger to a specific file rather than the current global match

https://github.com/openrewrite/rewrite-github-actions/blob/main/src/main/java/org/openrewrite/github/AddCronTrigger.java#L47-L53

**Comment by timtebeek** [comment]
The suggestion here is to use preconditions instead, as otherwise we would have to add file pattern options to every recipe.
https://docs.openrewrite.org/reference/yaml-format-reference#using-preconditions-to-limit-what-files-are-touched
